import { AppWindow, Bot, BriefcaseBusiness, ChartNoAxesCombined, CloudCog, RadioTower } from "lucide-react";

export const services = [
  {
    slug: "ai-automation-agents",
    number: "01",
    eyebrow: "Intelligent workflows",
    title: "AI Automation & Agents",
    headline: "Give repetitive work a dependable operating system.",
    copy: "We design task-specific AI agents that understand context, use approved business knowledge, coordinate work across systems, and involve people at the right decision points.",
    overview: "CreativeX builds governed AI agents for customer operations, knowledge work, document workflows, and internal coordination. The goal is not autonomous behavior for its own sake. It is a reliable improvement to a real workflow, with visible evidence and a clear path to human review.",
    details: ["Workflow orchestration", "Agent systems", "Human-in-the-loop controls"],
    features: ["Business process and decision mapping", "Retrieval from approved knowledge sources", "Tool use across CRM, messaging, orders, and internal systems", "Evaluation, confidence, escalation, and audit trails", "Omnichannel customer and employee experiences"],
    useCases: ["Lead capture, qualification, and follow-up", "Customer support and order coordination", "Document review and operational triage", "Internal knowledge and research assistance"],
    process: ["Frame the workflow and decision rights", "Prototype with representative scenarios", "Connect approved systems and data", "Evaluate, pilot, and improve in production"],
    controls: ["Permissions and least-privilege access", "Source visibility and traceable actions", "Human approval for consequential decisions", "Fallback behavior and continuous evaluation"],
    outcomes: ["Fewer missed or delayed tasks", "More consistent customer follow-through", "Clearer oversight of automated work"],
    icon: Bot,
  },
  {
    slug: "data-predictive-analytics",
    number: "02",
    eyebrow: "Decision intelligence",
    title: "Data & Predictive Analytics",
    headline: "Turn fragmented data into decisions people can use.",
    copy: "We turn fragmented operational data into reliable foundations, forecasting models, and decision tools that make patterns, risks, and opportunities easier to act on.",
    overview: "CreativeX connects operational data, improves its reliability, and translates analysis into practical decision experiences. We design the data foundation, model, interface, and operating loop together so predictions reach the people who can act on them.",
    details: ["Data platforms", "Predictive models", "Decision dashboards"],
    features: ["Data architecture and source integration", "Cleaning, transformation, and quality controls", "Forecasting, classification, and anomaly detection", "Operational dashboards and decision workspaces", "Model monitoring and explanation"],
    useCases: ["Demand and inventory forecasting", "Shipment and delivery exception prediction", "Customer and revenue intelligence", "Equipment, facility, and service analytics"],
    process: ["Define the decision and measurable baseline", "Assess data quality and availability", "Build and validate the analytical approach", "Deliver insights inside the operating workflow"],
    controls: ["Data lineage and access governance", "Performance tested against a baseline", "Clear confidence and limitation reporting", "Drift and data-quality monitoring"],
    outcomes: ["Earlier awareness of operational risk", "Faster, more consistent decisions", "A trusted data foundation for future products"],
    icon: ChartNoAxesCombined,
  },
  {
    slug: "iot-smart-operations",
    number: "03",
    eyebrow: "Connected operations",
    title: "IoT & Smart Operations",
    headline: "Connect physical signals to coordinated action.",
    copy: "We connect assets, environments, and teams through real-time telemetry, operational control tools, alerting, and intelligence that supports faster field decisions.",
    overview: "CreativeX develops connected-operation platforms that bring device data, business context, alerts, and field workflows into one usable environment. Systems are designed for resilience, clear ownership, and the realities of people working across facilities and the field.",
    details: ["IoT architecture", "Telemetry & alerts", "Operations control rooms"],
    features: ["Device, sensor, and gateway architecture", "Real-time telemetry and event processing", "Rules, anomaly detection, and alert orchestration", "Operations dashboards and mobile field tools", "Integration with maintenance and business systems"],
    useCases: ["Smart facility and energy monitoring", "Equipment health and preventive maintenance", "Cold-chain and environmental visibility", "Connected logistics and asset tracking"],
    process: ["Map assets, signals, and field decisions", "Validate connectivity and data quality", "Build the control and response experience", "Pilot, observe, and expand by site or asset class"],
    controls: ["Secure device identity and communication", "Offline and degraded-mode behavior", "Alert ownership and escalation paths", "Telemetry health and system observability"],
    outcomes: ["Earlier response to operational issues", "Less manual monitoring and coordination", "More visible facility and asset performance"],
    icon: RadioTower,
  },
  {
    slug: "web-mobile-product-engineering",
    number: "04",
    eyebrow: "Digital products",
    title: "Web & Mobile Product Engineering",
    headline: "Design the product and the system behind it.",
    copy: "We design and engineer secure digital products—from customer platforms and internal portals to mobile field tools—with one accountable team from discovery to release.",
    overview: "CreativeX combines product strategy, interface design, software engineering, and delivery into one connected practice. We build new products and modernize important workflows with an emphasis on usability, maintainability, security, and measurable adoption.",
    details: ["Product strategy", "Web platforms", "Mobile applications"],
    features: ["Product discovery and experience design", "Responsive web applications and portals", "Cross-platform and field-ready mobile products", "API and system integration", "Testing, analytics, accessibility, and delivery automation"],
    useCases: ["Customer self-service and commerce platforms", "Operational portals and internal tools", "Mobile tools for field and frontline teams", "AI-native SaaS and digital products"],
    process: ["Clarify users, jobs, and product outcomes", "Prototype the core experience", "Engineer and integrate the production system", "Release, measure adoption, and iterate"],
    controls: ["Secure identity and role-based access", "Accessible and responsive interaction", "Automated testing and release controls", "Performance and product observability"],
    outcomes: ["A clearer and more useful customer experience", "Faster learning with real users", "A maintainable foundation for product growth"],
    icon: AppWindow,
  },
  {
    slug: "cloud-solutions",
    number: "05",
    eyebrow: "Modern infrastructure",
    title: "Cloud Solutions",
    headline: "Build a cloud foundation the product can depend on.",
    copy: "We create resilient cloud foundations, modernize applications, and build delivery platforms with security, observability, and operating cost considered from the beginning.",
    overview: "CreativeX helps teams move from fragile infrastructure to secure, observable, and repeatable cloud operations. Architecture choices are connected to the product roadmap, team capabilities, compliance needs, and total operating cost.",
    details: ["Cloud architecture", "Platform engineering", "Security & observability"],
    features: ["Cloud architecture and workload assessment", "Application and data-platform modernization", "Infrastructure automation and delivery pipelines", "Identity, security, backup, and recovery design", "Monitoring, observability, and cost visibility"],
    useCases: ["New SaaS and AI product foundations", "Legacy application modernization", "Secure data and integration platforms", "Reliable multi-environment delivery"],
    process: ["Assess workloads, risks, and constraints", "Design the target platform and migration path", "Automate infrastructure and delivery", "Migrate safely and establish operating practices"],
    controls: ["Least-privilege identity and access", "Encrypted data and managed secrets", "Backup, recovery, and incident readiness", "Cost, performance, and reliability monitoring"],
    outcomes: ["More dependable product delivery", "Clearer security and operating visibility", "Infrastructure that can evolve with demand"],
    icon: CloudCog,
  },
  {
    slug: "ai-business-consultation",
    number: "06",
    eyebrow: "Direction before delivery",
    title: "AI Business Consultation",
    headline: "Turn AI ambition into a decision-ready roadmap.",
    copy: "We help leadership teams assess readiness, prioritize high-value use cases, define governance, and turn AI ambition into a sequenced roadmap the organization can execute.",
    overview: "CreativeX works with business and technology leaders to identify where AI can create credible value, what must be true for delivery, and which risks require explicit control. The result is a practical sequence of decisions and experiments—not a generic innovation presentation.",
    details: ["AI readiness", "Use-case portfolio", "Governance roadmap"],
    features: ["Workflow and opportunity discovery", "Data, technology, and operating-readiness assessment", "Use-case value, feasibility, and risk prioritization", "Responsible-AI and governance design", "Prototype and implementation roadmap"],
    useCases: ["Enterprise AI strategy and portfolio planning", "Agent and automation opportunity assessment", "AI product and platform direction", "Governance, policy, and adoption planning"],
    process: ["Interview stakeholders and map priority work", "Assess data, systems, teams, and constraints", "Prioritize opportunities with visible criteria", "Define experiments, governance, and delivery sequence"],
    controls: ["Explicit decision ownership", "Use-case risk classification", "Data and model governance requirements", "Measurable pilot success and stop criteria"],
    outcomes: ["A focused portfolio of credible opportunities", "Shared leadership understanding of risk", "A roadmap teams can fund and execute"],
    icon: BriefcaseBusiness,
  },
] as const;

export function getService(slug: string) {
  return services.find((service) => service.slug === slug);
}
