import { Handshake, Hotel, Rocket, Ship, Store } from "lucide-react";

export const solutions = [
  {
    slug: "export-logistics",
    number: "01",
    label: "Export & Logistics",
    headline: "Move goods with fewer blind spots and manual hand-offs.",
    copy: "Connect shipment data, documents, teams, and exceptions in one operating layer so people can see what needs attention and act before delays become customer problems.",
    capabilities: ["Document and compliance automation", "Predictive ETA and exception handling", "Shipment visibility and customer portals"],
    outcomes: ["Faster exception response", "Clearer operational visibility", "Less repetitive coordination"],
    system: "Operations intelligence platform",
    icon: Ship,
  },
  {
    slug: "hospitality-smart-facilities",
    number: "02",
    label: "Hospitality & Smart Facilities",
    headline: "Turn buildings into responsive operating environments.",
    copy: "Bring occupancy, energy, equipment, service requests, and staff workflows together to improve guest experience while making facilities easier to monitor and operate.",
    capabilities: ["Occupancy and energy intelligence", "Preventive maintenance workflows", "Guest and staff service automation"],
    outcomes: ["Earlier maintenance action", "Better service coordination", "More efficient facility use"],
    system: "Smart facility command center",
    icon: Hotel,
  },
  {
    slug: "retail-distribution",
    number: "03",
    label: "Retail & Distribution",
    headline: "Connect demand, inventory, orders, and frontline decisions.",
    copy: "Create a clearer view from warehouse to shelf with forecasting, order orchestration, and practical tools for teams managing stock, fulfillment, and customer demand.",
    capabilities: ["Demand and inventory forecasting", "Order and fulfillment orchestration", "Warehouse and field mobile tools"],
    outcomes: ["Better replenishment decisions", "Fewer operational surprises", "Faster order resolution"],
    system: "Distribution decision platform",
    icon: Store,
  },
  {
    slug: "professional-services",
    number: "04",
    label: "Professional Services",
    headline: "Make firm knowledge easier to find, apply, and scale.",
    copy: "Give teams governed access to trusted knowledge, automate repeatable document work, and create visibility across proposals, engagements, and client delivery.",
    capabilities: ["Knowledge and research copilots", "Proposal and document automation", "Client delivery dashboards"],
    outcomes: ["Faster knowledge access", "More consistent delivery", "Less administrative work"],
    system: "Firm intelligence workspace",
    icon: Handshake,
  },
  {
    slug: "startups-saas-products",
    number: "05",
    label: "Startups & SaaS Products",
    headline: "Build the right product, then build it to scale.",
    copy: "Work with a senior product and engineering team to shape an AI-native opportunity, validate the core experience, and deliver a secure cloud product ready for real customers.",
    capabilities: ["AI-native product discovery", "MVP-to-scale engineering", "Cloud platform and product analytics"],
    outcomes: ["Faster product learning", "A credible production foundation", "Clearer roadmap decisions"],
    system: "AI-native SaaS platform",
    icon: Rocket,
  },
] as const;

